/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'borgert' at '6/1/17 8:55 PM' with Gradle 3.0
 *
 * @author borgert, @date 6/1/17 8:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
